/* Generated by GOB (v2.0.17)   (do not edit directly) */

#ifndef __NOTIFYING_STRING_PRIVATE_H__
#define __NOTIFYING_STRING_PRIVATE_H__

#include "notifying-string.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _NotifyingStringPrivate {
#line 4 "common/notifying-string.gob"
	gchar * value;
#line 16 "notifying-string-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
